apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-webserver-ingress
  annotations:
    kubernetes.io/spec.ingressClassName: "nginx" 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: web.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache-webserver
            port:
              number: 80
