---
k3s_version: v1.25.9+k3s1
cni_plugins_version: v1.1.1
systemd_dir: /etc/systemd/system
zone: "{{ hostvars[inventory_hostname]['zone'] }}"
hostname: "{{ hostvars[inventory_hostname]['ansible_hostname'] }}"
master_ip: "{{ hostvars[groups['master'][0]]['ansible_facts'][hostvars[groups['master'][0]]['cluster_management_interface']]['ipv4']['address'] }}"
extra_server_args: '--node-label topology.kubernetes.io/zone={{ zone }} --cluster-cidr="172.16.0.0/14" --service-node-port-range="6789-40000" --write-kubeconfig-mode 644 --kube-proxy-arg "metrics-bind-address=0.0.0.0:9997" --kube-proxy-arg "healthz-bind-address=0.0.0.0:9996" --kubelet-arg="read-only-port=9995" --kubelet-arg="healthz-port=9994" --kubelet-arg="--port=9998" --tls-san="ha.gogo.yoducks.com" --etcd-expose-metrics=true --kube-scheduler-arg="bind-address=0.0.0.0" --kube-scheduler-arg="secure-port=9992" --kube-controller-manager-arg="bind-address=0.0.0.0" --kube-controller-manager-arg="secure-port=9993"'
extra_agent_args: ""
cluster_management_interface: eth0
