zone: "{{ hostvars[inventory_hostname]['zone'] }}"
extra_agent_args: '--node-label nodeType=utility --node-label topology.kubernetes.io/zone={{ zone }} --kube-proxy-arg "metrics-bind-address=0.0.0.0:9997" --kube-proxy-arg "healthz-bind-address=0.0.0.0:9996" --kubelet-arg="read-only-port=9995" --kubelet-arg="healthz-port=9994" --kubelet-arg="--port=9998"'
