---
- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755
  notify: Restart K3s service

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: started
    enabled: yes
